### ISSUE TITLE
modprobe.d input disables microphone

### ISSUE THREAD

**Issue by d-dmg** [PJungkamp/yoga9-linux#5]
fellow yoga user; i've noticed that enabling these options in the kernel modules disables microphone. Is this also occurring for you?

**Comment by pjungkamp** [comment]
The modprobe option forces the legacy HDA driver which does not support DMIC on newer hardware. So that's expected. I included the modprobe file for others to check whether the patch I've submitted for my Yoga works for their device too.

See the sof project documentation for more information:
https://thesofproject.github.io/latest/getting_started/intel_debug/introduction.html
